Fix/article CRUD
amaurymn/p5-oc-blog-php pull request #49
Opened 2020-10-24 08:21 UTC by amaurymn

2020-10-26 09:34 UTC, Tutt-J requested changes

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $article->setCreatedAt(new \DateTime());
You must add this directly on Timestamplable entity

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $article = new Article(['admin_id' => 1]);
Call it when form is submit

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        if ($this->isFormSubmit('publish')) {
refactore order with function like $form->isValid()

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
>      public function executeShowArticleList()
Rename executeReadList

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
>      public function executeShowArticleAdd()
Rename it executeCreate

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
>      public function executeShowArticleEdit()
Rename executeUpdate

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $getArticle  = (new ArticleManager())->findOneBy(['id' => $this->params['articleId']]);
Rename $article

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $editArticle = new Article(['admin_id' => 1, 'id' => $getArticle['id']]);
Remove this you must use $article

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +    public function executeDeleteArticle(): void
executeDelete

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $getArticle = (new ArticleManager())->findOneBy(['id' => $this->params['articleId']]);
rename $article

2020-10-26 09:34 UTC, Tutt-J commented on src/Controllers/AdminController/ArticleController.php
> +        $article    = new Article(['id' => $getArticle['id']]);
rename deleteArticle or remove

2020-10-26 09:34 UTC, Tutt-J commented on src/Core/Manager.php
> +        return $this->findBy($where, $order, 0, 1);
You must leave [0] you must administrate case where nothing is found

2020-11-01 14:56 UTC, amaurymn commented on src/Core/Manager.php
> +        return $this->findBy($where, $order, 0, 1);
`Undefined offset` si je supprime [0]
Il n'y a pas d'index car la fonction `findBy` utilise `fetch` si il y a 1 résultat et `fetchAll` si il y en a plusieurs.

fonction findBy
`return ($stmt->rowCount() > 1) ? $stmt->fetchAll() : $stmt->fetch();`

2020-11-06 17:30 UTC, merged